2021-12-07 12:56:35.668142: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: :/home/shandilya/.mujoco/mjpro150/bin
2021-12-07 12:56:35.668192: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
/home/shandilya/Desktop/Projects/NavigationController
Using cpu device
Sufficient Memory Available. Using 7.603728 GB with 10.704064512 GB available
Logging to assets/out/models/exp9/TD3_6
---------------------------------
| rollout/           |          |
|    ep_len_mean     | 2e+03    |
|    ep_rew_mean     | -238     |
| time/              |          |
|    episodes        | 4        |
|    fps             | 35       |
|    time_elapsed    | 227      |
|    total timesteps | 8004     |
---------------------------------
Eval num_timesteps=10000, episode_reward=-183.59 +/- 153.17
Episode length: 2001.00 +/- 0.00
---------------------------------
| eval/              |          |
|    mean_ep_length  | 2e+03    |
|    mean_reward     | -184     |
| time/              |          |
|    total_timesteps | 10000    |
---------------------------------
Terminated
2021-12-07 13:11:23.847164: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: :/home/shandilya/.mujoco/mjpro150/bin
2021-12-07 13:11:23.847204: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
/home/shandilya/Desktop/Projects/NavigationController
Using cpu device
Sufficient Memory Available. Using 7.603728 GB with 10.698153984 GB available
Logging to assets/out/models/exp9/TD3_7
---------------------------------
| rollout/           |          |
|    ep_len_mean     | 2e+03    |
|    ep_rew_mean     | -32.4    |
| time/              |          |
|    episodes        | 4        |
|    fps             | 34       |
|    time_elapsed    | 228      |
|    total timesteps | 8004     |
---------------------------------
Terminated
2021-12-07 13:18:53.687933: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: :/home/shandilya/.mujoco/mjpro150/bin
2021-12-07 13:18:53.687977: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
/home/shandilya/Desktop/Projects/NavigationController
Using cpu device
Sufficient Memory Available. Using 7.603728 GB with 10.785902592 GB available
Logging to assets/out/models/exp9/TD3_8
---------------------------------
| rollout/           |          |
|    ep_len_mean     | 1.25e+03 |
|    ep_rew_mean     | 156      |
| time/              |          |
|    episodes        | 4        |
|    fps             | 33       |
|    time_elapsed    | 147      |
|    total timesteps | 5000     |
---------------------------------
---------------------------------
| rollout/           |          |
|    ep_len_mean     | 1.19e+03 |
|    ep_rew_mean     | 116      |
| time/              |          |
|    episodes        | 8        |
|    fps             | 34       |
|    time_elapsed    | 276      |
|    total timesteps | 9528     |
---------------------------------
Eval num_timesteps=10000, episode_reward=-94.69 +/- 123.63
Episode length: 2001.00 +/- 0.00
---------------------------------
| eval/              |          |
|    mean_ep_length  | 2e+03    |
|    mean_reward     | -94.7    |
| time/              |          |
|    total_timesteps | 10000    |
---------------------------------
Terminated
Traceback (most recent call last):
  File "/root/tools/google-cloud-sdk/lib/third_party/packaging/version.py", line 31, in parse
    return Version(version)
  File "/root/tools/google-cloud-sdk/lib/third_party/packaging/version.py", line 202, in __init__
    raise InvalidVersion("Invalid version: '{0}'".format(version))
packaging.version.InvalidVersion: Invalid version: '.so'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/tools/google-cloud-sdk/lib/gcloud.py", line 104, in <module>
    main()
  File "/root/tools/google-cloud-sdk/lib/gcloud.py", line 76, in main
    gcloud_main = _import_gcloud_main()
  File "/root/tools/google-cloud-sdk/lib/gcloud.py", line 56, in _import_gcloud_main
    import googlecloudsdk.gcloud_main
  File "/root/tools/google-cloud-sdk/lib/googlecloudsdk/gcloud_main.py", line 34, in <module>
    from googlecloudsdk.calliope import base
  File "/root/tools/google-cloud-sdk/lib/googlecloudsdk/calliope/base.py", line 32, in <module>
    from googlecloudsdk.calliope import display
  File "/root/tools/google-cloud-sdk/lib/googlecloudsdk/calliope/display.py", line 37, in <module>
    from googlecloudsdk.calliope import display_taps
  File "/root/tools/google-cloud-sdk/lib/googlecloudsdk/calliope/display_taps.py", line 46, in <module>
    from googlecloudsdk.core.resource import resource_printer_base
  File "/root/tools/google-cloud-sdk/lib/googlecloudsdk/core/resource/resource_printer_base.py", line 47, in <module>
    from googlecloudsdk.core.resource import resource_projector
  File "/root/tools/google-cloud-sdk/lib/googlecloudsdk/core/resource/resource_projector.py", line 71, in <module>
    import proto  # pylint: disable=g-import-not-at-top
  File "/root/tools/google-cloud-sdk/lib/third_party/proto/__init__.py", line 15, in <module>
    from .enums import Enum
  File "/root/tools/google-cloud-sdk/lib/third_party/proto/enums.py", line 17, in <module>
    from google.protobuf import descriptor_pb2
  File "/root/tools/google-cloud-sdk/lib/third_party/google/protobuf/__init__.py", line 37, in <module>
    __import__('pkg_resources').declare_namespace(__name__)
  File "/root/tools/google-cloud-sdk/lib/third_party/pkg_resources/__init__.py", line 3030, in <module>
    @_call_aside
  File "/root/tools/google-cloud-sdk/lib/third_party/pkg_resources/__init__.py", line 3014, in _call_aside
    f(*args, **kwargs)
  File "/root/tools/google-cloud-sdk/lib/third_party/pkg_resources/__init__.py", line 3063, in _initialize_master_working_set
    list(map(working_set.add_entry, sys.path))
  File "/root/tools/google-cloud-sdk/lib/third_party/pkg_resources/__init__.py", line 694, in add_entry
    for dist in find_distributions(entry, True):
  File "/root/tools/google-cloud-sdk/lib/third_party/pkg_resources/__init__.py", line 2010, in find_on_path
    path_item_entries = _by_version_descending(os.listdir(path_item))
  File "/root/tools/google-cloud-sdk/lib/third_party/pkg_resources/__init__.py", line 1994, in _by_version_descending
    return sorted(names, key=_by_version, reverse=True)
  File "/root/tools/google-cloud-sdk/lib/third_party/pkg_resources/__init__.py", line 1992, in _by_version
    return [packaging.version.parse(part) for part in parts]
  File "/root/tools/google-cloud-sdk/lib/third_party/pkg_resources/__init__.py", line 1992, in <listcomp>
    return [packaging.version.parse(part) for part in parts]
  File "/root/tools/google-cloud-sdk/lib/third_party/packaging/version.py", line 33, in parse
    return LegacyVersion(version)
  File "/root/tools/google-cloud-sdk/lib/third_party/packaging/version.py", line 76, in __init__
    self._key = _legacy_cmpkey(self._version)
  File "/root/tools/google-cloud-sdk/lib/third_party/packaging/version.py", line 141, in _legacy_cmpkey
    for part in _parse_version_parts(version.lower()):
  File "/root/tools/google-cloud-sdk/lib/third_party/packaging/version.py", line 115, in _parse_version_parts
    for part in _legacy_version_component_re.split(s):
  File "/root/tools/google-cloud-sdk/lib/googlecloudsdk/core/util/lazy_regex.py", line 45, in __getattr__
    def __getattr__(self, name):
KeyboardInterrupt
2021-12-07 18:56:49.086787: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /usr/lib/nvidia-470:/usr/local/cuda/lib64:/root/.mujoco/mjpro150/bin:/usr/local/nvidia/lib:/usr/local/nvidia/lib64
2021-12-07 18:56:49.091188: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
/root/trainer
Using cuda device
Logging to assets/out/models/exp9/TD3_10
Found 1 GPUs for rendering. Using device 0.
Terminated
2021-12-07 19:00:54.084009: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /usr/lib/nvidia-470:/usr/local/cuda/lib64:/root/.mujoco/mjpro150/bin:/usr/local/nvidia/lib:/usr/local/nvidia/lib64
2021-12-07 19:00:54.084078: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
/root/trainer
Using cuda device
Sufficient Memory Available. Using 7.603728 GB with 30.166822912 GB available
Logging to assets/out/models/exp9/TD3_11
Terminated
2021-12-07 19:01:40.931418: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /usr/lib/nvidia-470:/usr/local/cuda/lib64:/root/.mujoco/mjpro150/bin:/usr/local/nvidia/lib:/usr/local/nvidia/lib64
2021-12-07 19:01:40.931511: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
/root/trainer
Using cuda device
Sufficient Memory Available. Using 27.64992 GB with 30.167650304 GB available
Logging to assets/out/models/exp9/TD3_12
Terminated
2021-12-07 19:02:34.766220: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /usr/lib/nvidia-470:/usr/local/cuda/lib64:/root/.mujoco/mjpro150/bin:/usr/local/nvidia/lib:/usr/local/nvidia/lib64
2021-12-07 19:02:34.766298: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
/root/trainer
Using cuda device
Sufficient Memory Available. Using 24.884928 GB with 30.164742144 GB available
Logging to assets/out/models/exp9/TD3_13
Found 1 GPUs for rendering. Using device 0.
Terminated
2021-12-07 19:05:06.207420: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /usr/lib/nvidia-470:/usr/local/cuda/lib64:/root/.mujoco/mjpro150/bin:/usr/local/nvidia/lib:/usr/local/nvidia/lib64
2021-12-07 19:05:06.207501: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
/root/trainer
Using cuda device
Sufficient Memory Available. Using 24.884928 GB with 30.168682496 GB available
Logging to assets/out/models/exp9/TD3_14
Found 1 GPUs for rendering. Using device 0.
Terminated
2021-12-07 19:06:53.152626: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /usr/lib/nvidia-470:/usr/local/cuda/lib64:/root/.mujoco/mjpro150/bin:/usr/local/nvidia/lib:/usr/local/nvidia/lib64
2021-12-07 19:06:53.152714: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
/root/trainer
Using cuda device
Sufficient Memory Available. Using 24.884928 GB with 30.165602304 GB available
Logging to assets/out/models/exp9/TD3_15
Found 1 GPUs for rendering. Using device 0.
Terminated
2021-12-07 19:09:20.417348: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /usr/lib/nvidia-470:/usr/local/cuda/lib64:/root/.mujoco/mjpro150/bin:/usr/local/nvidia/lib:/usr/local/nvidia/lib64
2021-12-07 19:09:20.417414: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
/root/trainer
Using cuda device
Sufficient Memory Available. Using 24.884928 GB with 30.20961792 GB available
Logging to assets/out/models/exp9/TD3_16
Found 1 GPUs for rendering. Using device 0.
Terminated
/root/trainer
Traceback (most recent call last):
  File "train.py", line 2, in <module>
    from learning.explore import Explore
  File "/root/trainer/learning/explore.py", line 64
    verbose = 2,
          ^
SyntaxError: invalid syntax
2021-12-07 19:33:32.983671: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /usr/lib/nvidia-470:/usr/local/cuda/lib64:/root/.mujoco/mjpro150/bin:/usr/local/nvidia/lib:/usr/local/nvidia/lib64
2021-12-07 19:33:32.983747: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
/root/trainer
Using cuda device
Sufficient Memory Available. Using 24.884928 GB with 30.173294592 GB available
Logging to assets/out/models/exp9/TD3_17
Found 1 GPUs for rendering. Using device 0.
[W python_anomaly_mode.cpp:104] Warning: Error detected in ExpBackward. Traceback of forward call that caused the error:
  File "train.py", line 46, in <module>
    model.learn(args.timesteps)
  File "/root/trainer/learning/explore.py", line 91, in learn
    callback = self.rl_callback
  File "/root/trainer/utils/td3_utils.py", line 982, in learn
    reset_num_timesteps=reset_num_timesteps,
  File "/usr/local/lib/python3.6/site-packages/stable_baselines3/common/off_policy_algorithm.py", line 369, in learn
    self.train(batch_size=self.batch_size, gradient_steps=gradient_steps)
  File "/root/trainer/utils/td3_utils.py", line 936, in train
    actions, vt, bg_out = self.actor(replay_data.observations)
  File "/usr/local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/root/trainer/utils/td3_utils.py", line 107, in forward
    return self.mu(features)
  File "/usr/local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/root/trainer/bg/models.py", line 225, in forward
    bg_out, vt  = self.bg([stimulus_t, stimulus_t_1])
  File "/usr/local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/root/trainer/bg/models.py", line 86, in forward
    lamd1 = 1 / (1 + torch.exp(-self.log_a1.exp() * (deltavf - self.thetad1)))
 (function _print_stack)
Traceback (most recent call last):
  File "train.py", line 46, in <module>
    model.learn(args.timesteps)
  File "/root/trainer/learning/explore.py", line 91, in learn
    callback = self.rl_callback
  File "/root/trainer/utils/td3_utils.py", line 982, in learn
    reset_num_timesteps=reset_num_timesteps,
  File "/usr/local/lib/python3.6/site-packages/stable_baselines3/common/off_policy_algorithm.py", line 369, in learn
    self.train(batch_size=self.batch_size, gradient_steps=gradient_steps)
  File "/root/trainer/utils/td3_utils.py", line 945, in train
    loss.backward()
  File "/usr/local/lib/python3.6/site-packages/torch/_tensor.py", line 255, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph, inputs=inputs)
  File "/usr/local/lib/python3.6/site-packages/torch/autograd/__init__.py", line 149, in backward
    allow_unreachable=True, accumulate_grad=True)  # allow_unreachable flag
RuntimeError: Function 'ExpBackward' returned nan values in its 0th output.
2021-12-07 20:21:08.426922: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /usr/lib/nvidia-470:/usr/local/cuda/lib64:/root/.mujoco/mjpro150/bin:/usr/local/nvidia/lib:/usr/local/nvidia/lib64
2021-12-07 20:21:08.427005: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
/root/trainer
Using cuda device
Sufficient Memory Available. Using 24.884928 GB with 30.172397568 GB available
Logging to assets/out/models/exp9/TD3_18
Found 1 GPUs for rendering. Using device 0.
----------------------------------
| rollout/            |          |
|    ep_len_mean      | 2e+03    |
|    ep_rew_mean      | 62.7     |
| time/               |          |
|    episodes         | 4        |
|    fps              | 4        |
|    time_elapsed     | 1948     |
|    total timesteps  | 8004     |
| train/              |          |
|    actor_loss       | -0.135   |
|    critic_loss      | 0.00753  |
|    learning_rate    | 0.0005   |
|    n_updates        | 1500     |
|    total_actor_loss | -0.132   |
|    value_loss       | 0.00334  |
----------------------------------
Terminated
2021-12-07 20:58:10.387801: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /usr/lib/nvidia-470:/usr/local/cuda/lib64:/root/.mujoco/mjpro150/bin:/usr/local/nvidia/lib:/usr/local/nvidia/lib64
2021-12-07 20:58:10.387890: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
/root/trainer
Using cuda device
Sufficient Memory Available. Using 24.884928 GB with 30.233317376 GB available
Logging to assets/out/models/exp9/TD3_19
Found 1 GPUs for rendering. Using device 0.
Terminated
2021-12-07 21:00:53.959144: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /usr/lib/nvidia-470:/usr/local/cuda/lib64:/root/.mujoco/mjpro150/bin:/usr/local/nvidia/lib:/usr/local/nvidia/lib64
2021-12-07 21:00:53.959226: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
/root/trainer
Using cuda device
Sufficient Memory Available. Using 24.884928 GB with 30.235582464 GB available
Logging to assets/out/models/exp9/TD3_20
Found 1 GPUs for rendering. Using device 0.
----------------------------------
| rollout/            |          |
|    ep_len_mean      | 2e+03    |
|    ep_rew_mean      | 73       |
| time/               |          |
|    episodes         | 4        |
|    fps              | 4        |
|    time_elapsed     | 1959     |
|    total timesteps  | 8004     |
| train/              |          |
|    actor_loss       | -0.178   |
|    critic_loss      | 0.00252  |
|    learning_rate    | 0.0005   |
|    n_updates        | 1500     |
|    total_actor_loss | -0.177   |
|    value_loss       | 0.00135  |
----------------------------------
